(() => {
  'use strict';
  const $ = (s, el=document) => el.querySelector(s);
  const state = {
    view:'office', sol:12.43, credits:8520, level:3, company:'RAVEN CAPITAL',
    market:{price:103.42, position:0, entry:0, pnl:0, seconds:204, history:[]},
    transactions:[
      ['Market payout','NASDAQ PIT #184','+1.87 SOL','green'],
      ['Office upgrade','Trading Desk LVL 2 → 3','-2,500 CR','red'],
      ['Deposit','From wallet','+10.00 SOL','green'],
      ['Employee salary','Analyst','-320 CR','red'],
      ['Market entry','DOW ROOM #021','-1.00 SOL','red']
    ],
    chat:[['WolfCapital','this is going higher'],['NovaFund','don’t get greedy'],['Rook','watch the close']]
  };
  for(let i=0;i<70;i++) state.market.history.push(100 + i*.045 + Math.sin(i*.42)*.32 + Math.sin(i*.13)*.22);

  function top(){return `<header class="top"><div class="chip"><b>${state.company}</b><small>LVL ${state.level} · DISCIPLINE PAYS.</small></div><div class="chip"><b>◉ ${state.sol.toFixed(2)} SOL</b><small class="green">+2.31</small></div><div class="chip"><b class="gold">★ ${state.credits.toLocaleString()}</b><small>CREDITS</small></div></header>`}
  const navItems=[['office','▥','OFFICE'],['city','⌖','CITY'],['market','▧','MARKETS'],['company','♙','COMPANY'],['finance','◉','FINANCE']];
  function nav(){return `<nav class="nav">${navItems.map(([v,i,l])=>`<button data-view="${v}" class="${state.view===v?'active':''}"><span>${i}</span>${l}</button>`).join('')}</nav>`}
  function office(){return `<section class="scene"><div class="sky"></div><div class="window"></div><div class="office-floor"></div><div class="desk main"></div><div class="monitor m1"></div><div class="monitor m2"></div><div class="desk side"></div><div class="desk finance"></div><div class="person p1"></div><div class="person p2"></div><div class="person p3"></div><div class="rug">SAME GAME<br>DIFFERENT HUNGER</div>
    <button class="hotspot h-news" data-action="news"><b>NEWSPAPER</b>Market news & results</button><button class="hotspot h-market" data-view="market"><b>TRADING TERMINAL</b>Enter markets</button><button class="hotspot h-analyst" data-action="analyst"><b>ANALYST</b>Data & statistics</button><button class="hotspot h-finance" data-view="finance"><b>FINANCE</b>SOL & transactions</button><button class="hotspot h-staff" data-view="company"><b>STAFF</b>Hire & manage</button><button class="hotspot h-city" data-view="city"><b>EXIT TO CITY</b>Explore district</button></section>`}
  function finance(){return `<main class="page"><h1>FINANCE</h1><div class="card"><div class="grid2"><div><div class="muted">SOL BALANCE</div><div class="big">${state.sol.toFixed(2)} SOL</div></div><div><div class="muted">CREDITS</div><div class="big gold">${state.credits.toLocaleString()}</div></div></div><div class="grid2" style="margin-top:14px"><button class="btn primary" data-action="deposit">↓ DEPOSIT SOL</button><button class="btn" data-action="withdraw">↑ WITHDRAW SOL</button></div></div><div class="card"><b>RECENT TRANSACTIONS</b>${state.transactions.map(t=>`<div class="tx"><div><b>${t[0]}</b><div class="muted">${t[1]}</div></div><b class="${t[3]}">${t[2]}</b></div>`).join('')}</div></main>`}
  function market(){let m=state.market;return `<main class="page"><div class="market-head"><div><h1 style="margin-bottom:2px">NASDAQ PIT #184</h1><div class="muted">12/12 PLAYERS · 10 MIN SESSION</div></div><div class="timer" id="timer">${fmt(m.seconds)}</div></div><canvas id="chart" width="760" height="430"></canvas><div class="card"><div class="row"><div><div class="muted">CURRENT PRICE</div><div class="big" id="price">${m.price.toFixed(2)}</div></div><div><div class="muted">YOUR POSITION</div><b id="pos">${m.position===0?'FLAT':m.position>0?'LONG':'SHORT'}</b></div><div><div class="muted">P&L</div><b id="pnl" class="${m.pnl>=0?'green':'red'}">${m.pnl.toFixed(3)} SOL</b></div></div></div><div class="card"><label class="muted">SIZE (SOL)</label><input id="size" class="size" type="number" inputmode="decimal" min="0.01" max="5" step="0.01" value="0.10"><div class="tradebox"><button class="btn primary" data-trade="1">↑ BUY / LONG</button><button class="btn danger" data-trade="-1">↓ SELL / SHORT</button></div><button class="btn" data-trade="0" style="width:100%;margin-top:8px">CLOSE POSITION</button></div><div class="card"><b>ROOM CHAT</b><div class="chat" id="chat">${state.chat.map(x=>`<p><b class="gold">${x[0]}:</b> ${x[1]}</p>`).join('')}</div><form class="chatbar" id="chatForm"><input id="chatInput" maxlength="90" placeholder="Message the room…"><button class="btn">SEND</button></form></div></main>`}
  function city(){return `<section class="city"><div class="building b1"></div><div class="building b2"></div><div class="building b3"></div><div class="citylabel">FINANCIAL DISTRICT · More locations unlock with office progression</div></section>`}
  function company(){return `<main class="page"><h1>RAVEN CAPITAL</h1><div class="card"><div class="row"><div><b>Trading Desk</b><div class="muted">Market access</div></div><b class="gold">LVL 3</b></div></div><div class="card"><b>STAFF 3/4</b><div class="tx"><div><b>Trader</b><div class="muted">Executes your orders</div></div><span>LVL 2</span></div><div class="tx"><div><b>Analyst</b><div class="muted">Unlocks market intelligence</div></div><span>LVL 1</span></div><div class="tx"><div><b>Risk Manager</b><div class="muted">Exposure & limits</div></div><span>LVL 1</span></div></div><div class="card"><b>NEXT UNLOCK</b><p>Brokerage Desk · Office LVL 5</p><div style="height:8px;background:#080e17;border-radius:9px;overflow:hidden"><div style="width:60%;height:100%;background:var(--gold)"></div></div></div></main>`}
  function render(){$('#root').innerHTML=top()+(state.view==='office'?office():state.view==='finance'?finance():state.view==='market'?market():state.view==='city'?city():company())+nav(); bind(); if(state.view==='market') draw();}
  function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));document.querySelectorAll('[data-trade]').forEach(b=>b.onclick=()=>trade(+b.dataset.trade));let f=$('#chatForm');if(f)f.onsubmit=e=>{e.preventDefault();let i=$('#chatInput');let v=i.value.trim();if(v){state.chat.push(['You',v]);i.value='';render()}}}
  function action(a){if(a==='deposit'){state.sol+=1;state.transactions.unshift(['Deposit','Demo wallet','+1.00 SOL','green']);render()}else if(a==='withdraw'){state.sol=Math.max(0,state.sol-1);state.transactions.unshift(['Withdrawal','Demo wallet','-1.00 SOL','red']);render()}else alert(a==='news'?'THE WALL STREET TIMES\nRaven Capital takes the win.\nMarket rooms are active.':'Analyst: flow is balanced. No side has control yet.')}
  function trade(dir){let m=state.market, size=Math.max(.01,Math.min(5,parseFloat($('#size')?.value)||.1));if(dir===0){m.position=0;m.entry=0;m.pnl=0}else{m.position=dir*size;m.entry=m.price;m.pnl=0}render()}
  function fmt(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
  function draw(){let c=$('#chart');if(!c)return;let x=c.getContext('2d'),d=state.market.history,w=c.width,h=c.height,p=28,min=Math.min(...d)-.4,max=Math.max(...d)+.4;x.clearRect(0,0,w,h);x.strokeStyle='#172638';x.lineWidth=1;for(let i=0;i<6;i++){let y=p+(h-2*p)*i/5;x.beginPath();x.moveTo(p,y);x.lineTo(w-p,y);x.stroke()}x.strokeStyle='#23d18b';x.lineWidth=3;x.beginPath();d.forEach((v,i)=>{let xx=p+(w-2*p)*i/(d.length-1),yy=h-p-(v-min)/(max-min)*(h-2*p);i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke()}
  function tick(){if(state.market.seconds>0)state.market.seconds--;let m=state.market;let pressure=(Math.random()-.5)*.18;m.price=Math.max(1,m.price+pressure);m.history.push(m.price);if(m.history.length>90)m.history.shift();if(m.position)m.pnl=(m.price-m.entry)*m.position; if(state.view==='market'){let t=$('#timer'),p=$('#price'),pl=$('#pnl');if(t)t.textContent=fmt(m.seconds);if(p)p.textContent=m.price.toFixed(2);if(pl){pl.textContent=m.pnl.toFixed(3)+' SOL';pl.className=m.pnl>=0?'green':'red'}draw()}}
  render();setInterval(tick,1000);
})();
